### ISSUE TITLE
Legacy Update Don't Work In Windows 8.1 :(

### ISSUE THREAD

**Issue by HelloMan12345** [kirb/LegacyUpdate#112]
I Have A Small Problem While Installing Legacy Update:

Installing windows 8.1 update 1 cause this error message:
![Capture](https://user-images.githubusercontent.com/95941586/216008292-52c4761c-6dfe-4fe9-84a9-094697d85e91.PNG)

Any Fix For This ?

**Comment by kirb** [comment]
Seems to be the same issue as #104, will close this issue in favor of that one to keep track of fixing it. Basically, it's because it's trying to install Update 1, when you're already on Update 1 (likely more like Update 3 in fact). I need to fix the detection of which updates you need, or let it skip updates that return the "not applicable" error.
