### ISSUE TITLE
LegacyUpdate stays on LegacyUpdateTemp user after updating WUA and rebooting

### ISSUE THREAD

**Issue by justalemon** [kirb/LegacyUpdate#113]
Hi, I recently had this problem where I installed Legacy Update on a fresh Windows XP Professional x64 SP1 install. After it installed the Update Agent update and rebooted, it automatically logged into the LegacyUpdateTemp user and just didn't do anything.

![image](https://user-images.githubusercontent.com/11861253/216749014-3595bfc2-ce6f-49b6-a460-34d6423bb0f7.png)

I had to manually switch back to my regular user, where the update continued after that.

![image](https://user-images.githubusercontent.com/11861253/216749009-6cefa170-6ca3-4fbd-a16b-e3259fb82629.png)

**Comment by kirb** [comment]
Hm, feels to me that the temp account didn't get administrator privileges. Legacy Update launches itself on logon via the Windows RunOnce feature, which only triggers for administrator accounts. So if a non-admin logs on, it just goes straight to desktop. Possible my code that figures out the name of the Administrators group isn't working on XP x64. Will give it a test soon.

**Comment by renodr** [comment]
I can confirm this issue and did a bit of investigation:

![image](https://user-images.githubusercontent.com/11901488/223864499-a33ad25a-4d50-4cbc-af0c-d0a28042de00.png)

In this case, the LegacyUpdateTemp user succeeded in installing the update agent, root certificates, and checking SSL connectivity. For some reason though, it then proceeded to log in to the system, and no reboot occurred.

Running 'net user' shows that the LegacyUpdateTemp user no longer exists on the system, so that portion appears to work.

I've observed this behavior in Windows 2000 Server when trying to reproduce things for #42 as well.

I've got a couple of thoughts about this though. We've got two lines of code in RunOnce.nsh:

			RMDir /r /REBOOTOK "$PROFILE"
			System::Call "user32::ExitWindowsEx(i ${EWX_FORCEIFHUNG}, i 0) i .r0"

Checking [https://nsis.sourceforge.io/Reference/RMDir](url) shows that we cannot remove a directory if it contains the current working directory. I'm not sure if this affects us though, but we could change our current directory to $SYSDIR and then remove it. I'm not sure if this is where we're experiencing the problem though. I'll give that a test and see if anything changes.

Meanwhile, I can confirm that C:\Documents and Settings\LegacyUpdateTemp is still present.

![image](https://user-images.githubusercontent.com/11901488/223866657-2aed76f4-692a-4452-a41f-88c23f1a4b03.png)

Is it possible though that the call to ExitWindowsEx is not functioning correctly, and the profile is being created the rest of the way due to the system call not executing? I was wondering if running the 'Reboot' function is a safer bet instead, but I'd need to test that too.

Either way though, if I can fix this, I'll put in a PR!

**Comment by kirb** [comment]
Yeah the delete-then-logoff is kinda clunky. The problem is probably that logging off has some internal delays so running apps have a chance to respond to the logoff event, that seems to happen even despite not reaching the shell (explorer) yet. I wonder if the solution would be to `Sleep` for long enough that the `EWX_FORCEIFHUNG` flag kicks in and force terminates it, giving it no chance to continue to RunOnceEx ("Personalized Settings" dialog) and explorer. The logoff won’t happen for that long regardless, so it seems like the way to go.

Good point on current directory, I don’t know if RunOnce launches with the profile or system32 as current directory. Will experiment with it. I'm not sure if the profile can be nuked entirely because NTUSER.DAT will always be locked, that’s why the reboot is needed to fully remove it.

**Comment by renodr** [comment]
I've done a bit of experimental work on this and determined that even if we Sleep for 5 minutes, EWX_FORCEIFHUNG still doesn't kick in. I've changed it to EWX_FORCE and added a constant locally and that does seem to work, and the LegacyUpdateTemp user's profile is empty with the exception of the Application Data and Cookies folders and the expected NTUSER.DAT. However, once rebooting, the only thing left is 'ntuser.ini', which is good. This should be safe because we're only running as the RunOnce user anyway (if we were running as a standard user who might have things open, hesitation definitely makes more sense)

I added a couple more lines to RunOnce.nsh as a test to see where we're executing at:

```
System::Call "kernel32::GetCurrentDirectory(i ${NSIS_MAX_STRLEN}, t .r9)"
MessageBox MB_OK "$9"
```

This resulted in 
![LU RunOnce](https://user-images.githubusercontent.com/11901488/229314078-393ad648-0aae-4abb-a7a7-0f568cbd1124.PNG)
