### ISSUE TITLE
Can’t enable Microsoft Update on Windows 7

### ISSUE THREAD

**Issue by techflashYT** [kirb/LegacyUpdate#124]
I can't tell if it's enabled by default (I don't remember exactly what it updates).
But when I click the "Find out more" link, it opens IE to a forwarder page, which just takes me to Bing.

Is there a specific way that it need to be enabled to work with LegacyUpdate?

**Apologies if it is enabled by default and I'm just misremembering what it does!**

System Specs:
Laptop, Lenovo ThinkPad SL510
Mechanical HDD, 160GB, Dual boot with Linux, Windows Partition is 54.69GB at the end
Windows 7 SP1
Intel Core 2 Duo T6670, 2.20GHz
RAM: 4GB 800MHz

**Comment by kirb** [comment]
Hmm I should add something to let you enable that. I realised only more recently that 7 still took you to the Microsoft Update website, which of course no longer works. In 8 they replaced it with a simple checkbox. I misremembered and thought the checkbox was in 7, so we definitely need something equivalent to the checkbox for 7. 

The Legacy Update proxy server effectively enables Microsoft Update, but that’s only used up to Vista because those versions otherwise can’t receive updates at all. 7 and up have no issues with the official Microsoft server, so the Windows Update config isn’t touched in that case.

Microsoft Update gives you updates for other Microsoft products like Office, Visual Studio, etc. through Windows Update.

**Comment by renodr** [comment]
I think I have a powershell script that used to opt my systems into Microsoft Update sitting around here somewhere. In a past life, I was in charge of deploying Windows 7 to about 2000 computers at a school district, and manually enabling Microsoft Update on them (especially since sysprepping a Windows 7 system would take away the flag) would've been impossible

I'll post it here once I've had a chance to test that it still works. If I remember correctly you'd also need to restart the Windows Update and BITS services so they adjust their configuration

**Comment by kirb** [comment]
A checkbox to enable Microsoft Update on Windows 7 is now released in [Legacy Update 1.7](https://github.com/kirb/LegacyUpdate/discussions/169).
