### ISSUE TITLE
Issues with Windows 7 Enabling Microsoft Update

### ISSUE THREAD

**Issue by KBhalerao2000** [kirb/LegacyUpdate#186]
Hi, I have tried to use Legacy Update 1.8 to setup a fresh Windows 7 x64 VM, however it crashes at this stage. I am using the official media to install Windows 7 Ultimate X64 SP1 named en_windows_7_ultimate_with_sp1_x64_dvd_u_677332.iso with SHA1 of 36ae90defbad9d9539e649b193ae573b77a71c83. It looks like a fault with wuapi.dll version 7.6.7601.19161. Thanks again for this excellent project, have used it on many machines. This is also happening with x86 installs as well.

**Comment by kirb** [comment]
Thanks for reporting, I think it must not work if it’s done before the system has fully installed all the Windows Update Agent updates. Will work on this.

**Comment by coolusernamehere1223** [comment]
> Thanks for reporting, I think it must not work if it’s done before the system has fully installed all the Windows Update Agent updates. Will work on this.

Having the same issue here but with an pro 64 version.

**Comment by Preloading** [comment]
Have the same issue, took a photo tho
![20231007_211413](https://github.com/kirb/LegacyUpdate/assets/60761520/0dfa79f1-bac2-46ed-8d99-30e2d581495b)

**Comment by Hez0** [comment]
I'm also experiencing the installation crashing upon the Microsoft Update part. Not a fresh install.

**Comment by stasinek** [comment]
Hi. @kirb  I think i found solution?! I had issue installing 1.6, 1.7 and 1.8 on Windows 7 it was downloading certificates but crashing at next step enabling updates. Just as many people reported. It worked just fine on Vista and XP not on 7. In my case the problem was fact that i used WSUS Proxy. URLs for WUServer was invalid in my case local loopback adress. In case of older newly installed systems could be just outdated causing wuapi.dll crashing? Not fault of Legacy Update at all. My setup and links are on the screenshoot. Or eventually here https://www.elektroda.pl/rtvforum/topic3832843.html  I don't know what are original server adresses for Windows Update i just ran proxy server and problem solved 99% because i ran version 1.7 first. Will check out 1.8 later. I believe it will work. BTW. Bonus [https://retrosystemsrevival.blogspot.com/](https://retrosystemsrevival.blogspot.com/) or [msfn.org/board/](https://msfn.org/board/) including updates browsers for Windows XP, Windows Vista and 7 such as 360 Chrome v13 build 2250 based on Chromium 86 or DC Browser based on Chromium 75 etc.  Enjoy. 

Thanks for the app! Previously i was downloading certificates by myself from Firefox or CURL project. Your app automated this process. You are the best! 

BTW. Other reason could be fact servers are no longer active or require TLS 1.1 and 1.2 in Windows, but by default these are disabled and SSL2 enabled. That crucial update is probably provided by Legacy Updates as well? If not here is the manual. [https://learn.microsoft.com/en-US/mem/configmgr/core/plan-design/security/enable-tls-1-2-client](https://learn.microsoft.com/en-US/mem/configmgr/core/plan-design/security/enable-tls-1-2-client)   

> Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate]
> "WUServer"="http://127.0.0.1:8530/?"
> "WUStatusServer"="http://127.0.0.1:8530/?"
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU]
> "UseWUServer"=dword:00000001
> "NoAutoUpdate"=dword:00000000
> "AUOptions"=dword:00000002

 
![Screenshoot 2023-10-21 15 29 49](https://github.com/kirb/LegacyUpdate/assets/10685658/8cee7cb9-aae2-4bc9-9b2d-224f59ff3eed)

**Comment by Aurora-XP** [comment]
Hi,
Seen this issue but tried anyway cause 1 year ago it worked on an Windows 7 laptop.

Got same issue than Preloading, but worse ! while my Windows 7 installation is some days ago, i've noticed Legacy Update unpinned Firefox from taskbar (i did put back it) and reinitialized Start Menu... until I see that i'm now logged not with my name, but as "LegacyUserTemp".
![LegacyUpdatetemp](https://github.com/kirb/LegacyUpdate/assets/112265122/138e6142-3e5f-4e74-926c-2a9cc505ca73)

**Comment by Preloading** [comment]
> Hi,
> Seen this issue but tried anyway cause 1 year ago it worked on an Windows 7 laptop.
> 
> Got same issue than Preloading, but worse ! while my Windows 7 installation is some days ago, i've noticed Legacy Update unpinned Firefox from taskbar (i did put back it) and reinitialized Start Menu... until I see that i'm now logged not with my name, but as "LegacyUpdateTemp".
> 
> ![LegacyUpdatetemp](https://github.com/kirb/LegacyUpdate/assets/112265122/138e6142-3e5f-4e74-926c-2a9cc505ca73)
> 

I also had the issue with it logging into the user account. Running the installer again fixed it for me

**Comment by Preloading** [comment]
Temp Fix: Log out out LegacyUserTemp, Log into your own user, and rerun the setup, and untick Enable Microsoft Update, it should fix it, as a temp fix

**Comment by kirb** [comment]
Sorry it took me a while to get to this, but this has been fixed in Legacy Update 1.9!
