### ISSUE TITLE
Legacy Update not working on IE9 or later?

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [kirb/LegacyUpdate#19]
I was using Legacy Update to update an Acer Aspire 5515 on Windows Vista Home Basic 32-bit, and it was working fine up until I installed the IE9 update, after I installed IE9 Legacy Update started appearing like in the photo shown. After this, for testing purposes I installed Legacy Update on a Dell Inspiron N5030 running Windows 7 Home Premium 64-bit, worked fine on IE8, but when I updated to IE11, same thing as before. Anyone know what could be causing this?
![Capture](https://user-images.githubusercontent.com/78825510/203908111-32d71e9b-c64b-4c50-9419-aa5d3cf47ea7.PNG)

**Comment by kirb** [comment]
Unfortunately, it doesn't currently work in IE9-11 because the original Microsoft code uses a proprietary feature of earlier versions of JScript, that was removed from later versions to better follow standards. Since you're on Vista you should be able to use the Windows Update control panel anyway, but I'll still try and come up with a workaround when I can.

**Comment by kirb** [comment]
I seem to remember I wasn’t able to work around this by forcing the browser to IE8 compatibility mode, but I gave it another try and it seemed to work. In case that doesn’t work, I also added a check for IE9+ which will make it display an error message rather than a totally blank screen.
