### ISSUE TITLE
Installer fails if installing the SP3 update is enabled on XP x64

### ISSUE THREAD

**Issue by RUvlad1** [kirb/LegacyUpdate#24]
Stops after trying to install a XP SP3 update, if any additional info is needed please lmk

![image](https://user-images.githubusercontent.com/60317461/204580510-8c130348-ee83-415a-94fb-b9ca073ae9af.png)

![image](https://user-images.githubusercontent.com/60317461/204580545-baf19d58-a294-4bd0-b3d0-84ddba839b17.png)

**Comment by RUvlad1** [comment]
ok so legacy updater does work but the SP3 update makes it fail

**Comment by chungy** [comment]
SP2 is the last service pack for XP x64. SP3 is strictly 32-bit only.

**Comment by kirb** [comment]
Hm, so the `${IsWin2003}` check I used doesn't actually detect XP x64 like I assumed then, it strictly only detects Server 2003. Should be a straightforward fix, will work on this.

**Comment by kirb** [comment]
Fix will be in 1.3.1 which I'll release shortly. I had to work around NSIS's Windows version checking library (WinVer.nsh) because it does some special logic when it comes across XP version 2003 (5.2). It checks whether it's a client (XP x64) or server (2003), and if client, it overrides its internal version number to be that of XP version 2002 (5.1). That doesn't make sense for Legacy Update, we need to know the actual version number, so I've now written my own logic to check for XP 2002 vs 2003.

**Comment by kirb** [comment]
Released in 1.4, thanks for reporting.
