### ISSUE TITLE
Update Agent 7.4.7600.256 error 82 when installing on XP Home

### ISSUE THREAD

**Issue by Brds7t7** [kirb/LegacyUpdate#27]
Please remove the mandatory installation and reliance on WindowsUpdateAgent v7.6.
v7.6 Will not install on Windows XP Home - Error Code 82 (only installs correctly on XP Pro), but v7.4.7600.226 installs fine on XP Home. Windows Update MiniTool also works fine with v7.4 installed. So installer should just check for v7.4.7600.226 and allow the installation.

Here are the Direct MS links to WUA v7.4:

http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.226/windowsupdateagent30-x86.exe

http://download.windowsupdate.com/windowsupdate/redist/standalone/7.4.7600.226/windowsupdateagent30-x64.exe

**Comment by kirb** [comment]
I find that really unusual, because the VM I've been using for most of my testing is XP Home (I happened to have a CD of XP Home RTM), and I've tested the scenario of upgrading from RTM to SP3 a handful of times without issue, letting the setup auto install the 7.6.7600.256 build. Any 7.x build will work on XP, but I was trying to prefer the latest possible release that will work on your OS release, in the spirit of the project's goal to help you be as up to date as possible.

I'm just doing another SP3 upgrade path test now, we'll see what happens, maybe I've been completely inattentive to it (it's possible). I keep seeing this issue reported but I haven't been able to figure out how to reproduce.

If you want to bypass it for yourself, you can go to `%temp%`, find the `nsXXX.tmp` folder, and edit [this line](https://github.com/kirb/LegacyUpdate/blob/cf8dfbd4271c14f1553dff065d76825ef8a58f1a/activex/build/Patches.ini#L180) in Patches.ini. (Sorry, Notepad will be silly about that file because it has Unix line endings, best to use Wordpad instead.)

**Comment by kirb** [comment]
So, interesting, it does fail. I don't have a good answer for why I missed this all this time... Most likely the last time I did the full SP3 upgrade path was before I implemented the WUA updater logic in the setup.

What I'm very confused about is that it's not the actual installation that fails, it's the SFX extractor. I think we've finally root caused this problem :flushed: (/cc @InternalLoss)

![XP RTM-2022-12-01-19-21-29](https://user-images.githubusercontent.com/773309/205008291-f1e41529-9b5b-4cb6-a3da-1393c095dacd.png)

This is the problem I documented on the [FAQ](https://legacyupdate.net/faq). Manually extracting the cab out of WindowsUpdateAgent.exe, and then WUA-Downlevel.exe, bypasses the problem, but that's not exactly a good solution.

Best answer I can come up with is indeed to downgrade the WUA version we install to 7.4.7600.226. That's a bit of a shame because, again, the philosophy is to be as up to date as possible, and 256 was released specifically to harden WUA security. But it has to be done if the alternative is... uh, bricking your XP install with an "NTLDR is missing" error :woman_facepalming:

**Comment by robastala** [comment]
win home here, so the simple solution would be great thanks

**Comment by kirb** [comment]
Worked around for upcoming 1.4.1 release. XP Home will now install WUA 7.6.7600.243 rather than 7.6.7600.256. 243 the closest version to 256 that extracts without issues. In future I’d like to manually extract the cab from WindowsUpdateAgent-7.6-x86.exe, and then from WUA-Downlevel.exe, and then directly run wusetup.exe, which works fine, but this solves the problem for now.
