### ISSUE TITLE
Windows10 reports virus in LegacyUpdate.exe

### ISSUE THREAD

**Issue by avsteele** [kirb/LegacyUpdate#4]
Hi, I was interested in this project and was going to try it out on in WinXP x83 SP2 freshly installed, in a VMware instance.

1) The legacyupdate.net freezes internet explorer when I try to load it.

2) If I download LegacyUpdate.exe on a Win10 host I get an alert upon download that it contains "Trojan:Win32/Wacatac.H!ml"

**Comment by kirb** [comment]
Yes, that will be likely because it’s a very unknown file as far as AVs are aware, so they’re going to scan it with fairly generic heuristics. I did notice from a quick google that [someone else](https://answers.microsoft.com/en-us/protect/forum/all/wacatac-false-positive/fe8a49c1-faec-47fe-a2ca-7ea47968abcd) had an odd detection for it.

Interestingly it passes Microsoft AV [on VirusTotal](https://www.virustotal.com/gui/file/ebe8c5a5509d44a992e3deda87d9f230b88bc28eab5c26575a9a5e6c4476b55b/detection). You can have a look at the further analysis they provide to confirm that it basically just installs/registers LegacyUpdate.dll, sets some registry keys, and restarts the Windows Update service. Worth noting the AVs that return a result are mostly generic low confidence.

I think I know why IE6 is hanging, I made a JavaScript fix for it but I didn’t clear the Cloudflare cache. I’ll fix that in a moment.

**Comment by kirb** [comment]
Forgot to close this, IE6 hang is fixed and the AV issue has been explained. It seems the upcoming Legacy Update 1.1 might avoid AV detections, by luck because of how I've refactored some stuff. Or at least, Defender isn't complaining on my PC so far. I guess we'll see after a week or two. Specifically, the installer is now the far more common NSIS rather than Microsoft Wextract (IExpress), it installs to Program Files instead of System32, and I statically link the Visual C++ runtime rather than bundling the full redistributable installer.
