### ISSUE TITLE
compatibity Windows 9x

### ISSUE THREAD

**Issue by Quetcho** [kirb/LegacyUpdate#41]

**Comment by yotoprules** [comment]
Taken from the FAQ: https://legacyupdate.net/faq

What about Windows 95, 98, Me, and NT 4?

To explain this, here is a quick history of Windows Update:

    Version 3: Windows Update started life as a program called Critical Update Notification Tool (a very unfortunate acronym), which would nag you to open the Windows Update v3 website to download applicable updates for your system. Not all that intelligent - it was just a website that downloaded a massive (for the time) file listing every update ever released by Microsoft, filtering out the updates irrelevant to your system within the Windows Update website itself.

    Version 4: A total overhaul of how Windows Update works. Windows Update evolved from just a standalone file to a protocol, where the PC and the Microsoft server compare notes and figure out which updates are applicable to the current system. Included with Windows 2000 and XP, and installable as an update to Windows 98, Me, and NT 4. Also introduced Automatic Updates on 2000 and XP.

    Version 5 and 6: Windows Update v5 provided some major refinements to v4. Windows Update v6 added support for updating other Microsoft products along with Windows itself (confusingly named Microsoft Update), and is the most current version to this day. Included with Windows Vista right up to Windows 11, and installable as an update to Windows 2000 SP3 and XP RTM.

Legacy Update works because we’re lucky enough that the Windows Update v6 protocol is pretty much the same today as it was when the v6 protocol was first released around 2005. It seems unlikely that Microsoft will completely discontinue Windows Update for 2000/XP, though as I discussed in the [introduction paragraph](https://legacyupdate.net/), Microsoft has taken a very destructive approach to discontinuing services for old versions of Windows, right down to deleting legacy downloads and knowledge base articles from their servers, so that’s still an issue to be concerned about.

Given Windows Update is a protocol, and not a website Wayback Machine can easily scrape and archive, I’m concerned that this means the legacy Windows Update servers and the updates/drivers they provide are lost to time. Some, but not all, of Windows Update v3 has been preserved by the Wayback Machine, so I’m looking into what I can do there.

So the answer, pretty much, is that I’d love to support as far back as Windows Update itself has existed, but it may be quite a bit more significant undertaking than Legacy Update has been so far due to Microsoft’s intent to move on from its past. I’m still positive it can be done though!

**Comment by kirb** [comment]
Closing in favor of the main #9 thread about Win9x support.
