### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mx4address** [kirb/LegacyUpdate#45]
Legacy Update doesn't work on my XP installation. It keeps crashing and the guy behind this told me to put it in C: drive, it does not change anything. It continues crashing.

![image](https://user-images.githubusercontent.com/84406344/208179648-f56d2b44-0b5b-4ca4-b407-4e962fbe3922.png)

**Comment by exurd** [comment]
Having the same problem here. Using VMware Workstation Player 17 to emulate Windows XP SP3 RTM (Build 2600.xpsp.080413-2111).

**Comment by yotoprules** [comment]
Does it work work if you put it on the root of the C: drive and then run it from CMD?

**Comment by exurd** [comment]
No, the same thing occurs.

**Comment by MrPhil17** [comment]
Hi all,
I tried to start the file from desktop and C: (which helped a bit but crashes anyway), then I tried to login with Administrator, and the file from Administrator's Desktop installed flawlessly.
I use Windows XP Pro SP3 with Italian language.
Maybe this will help somebody else!

**Comment by exurd** [comment]
> then I tried to login with Administrator, and the file from Administrator's Desktop installed flawlessly.

Just tried this using explorer and cmd in the root of C: drive; did not work. On the desktop, it crashed instantly with no installation window.

**Comment by mheiniger** [comment]
I have 3 VirtualBox images of WinXP Pro with SP3 in german.
On all of them the installer crashed, sometimes in the beginning, sometime in the middle of installing.
Moving the installer to c:\ and running it from cmd worked for 2 vm's.
For the third it only helped to use Version 1.4.0 of LegacyUpdate. It was also the one WinXP which was most behind.

**Comment by exurd** [comment]
> For the third it only helped to use Version 1.4.0 of LegacyUpdate. It was also the one WinXP which was most behind and needed 44 windows updates.

I tried [version 1.4.0](https://github.com/kirb/LegacyUpdate/releases/tag/v1.4.0.0) and it worked!
Something in 1.4.1 must've broken support for SP3 RTM.

**Comment by mx4address** [comment]
but no one noticed my background :D

**Comment by mx4address** [comment]
THE FUCKING HELL WHO DISLIKED THAT

**Comment by mx4address** [comment]
sorry for those two posts i made earlier that someone noticed

**Comment by kirb** [comment]
@mx4address Please keep issue threads professional, thank you.

I’d assume the faulty code in question would be this: [`v1.4.0.0...v1.4.1.0`#diff-165639ec16](https://github.com/kirb/LegacyUpdate/compare/v1.4.0.0...v1.4.1.0#diff-165639ec165c7cd886cda9a2320b1cbe6d9c374725c813803c671a1c2e185da6R7-R11)

Not exactly expecting there to be that many people versed in NSIS out there, but in case the planets somehow align, does anyone happen to see anything wrong with what I’m doing there? I haven’t had a moment to properly sit down and investigate just yet, which is why I added the note and link to 1.4.0 on the homepage as a workaround for now.

Pasting these resources here mostly for my reference later on, but if anyone else wants to investigate these would get you started:

* Example of calling GetVersionEx() and pulling values out of the struct: https://nsis.sourceforge.io/Docs/System/System.html#structsizemember
* How WinVer.nsh calls GetVersionEx(): https://github.com/PortableApps/Launcher/blob/796039f886e40eab6380568ff72d465003d7f6dd/App/NSIS/Include/WinVer.nsh#L211-L250

**Comment by mx4address** [comment]
i don't care

**Comment by kirb** [comment]
Fixed in Legacy Update 1.5

**Comment by yotoprules** [comment]
> 

I have the same problem - on 1.4.1 and 1.5 it won't launch at all, if I copy it to the C:\ root drive then it will launch but crashes as soon as I click install. 1.4 works fine however.
