### ISSUE TITLE
Vista SP1 + SP2 very slow to download through LU

### ISSUE THREAD

**Issue by caraar12345** [kirb/LegacyUpdate#64]
👋 heyo, trying out Legacy Update with an RTM version of Vista because... fun (and it is fun - this is awesome). And for some reason, the SP1 and SP2 exe files are taking an unreasonable amount of time to download. Even though IE7 is able to download (at least the SP2 exe) at a normal speed.

Could it be worth adding a way by which to manually provide it with a service pack exe that you've sourced elsewhere? Obviously it's possible to just install the SP directly and then use LU afterwards, but being as the only part that seems to be an issue is the download, manually providing the file might be worthwhile 😁

**Comment by kirb** [comment]
You can actually put a file of matching name in the same directory as LegacyUpdate-1.x.exe, e.g. vistasp1.exe, and it'll use that rather than downloading it. But of course that's not super useful if you still have to dig around to find the download. Either way it seems like something might be wrong with the InetC.dll file downloader plugin I'm using when the system HDD or RAM isn't able to keep up with the internet connection. Someone else had that problem here: https://github.com/kirb/LegacyUpdate/discussions/36#discussioncomment-4551832. So I'll need to look into that.

**Comment by caraar12345** [comment]
Oh neat! Great to know for next time 👀 

In this case, it was Vista in a VM so... slowness is probably to be expected.

Perhaps the UI could allow you to copy the download links for things like that? As I'd bet a lot of people would like to be able to download larger files on another more capable machine then transfer them over by USB etc.

**Comment by kirb** [comment]
Handled in 1.6.2 by changing the downloader library from INetC to NSxfer.
