### ISSUE TITLE
Shortcut launches 64-bit instead of 32-bit IE on Windows XP x64

### ISSUE THREAD

**Issue by lichtmetzger** [kirb/LegacyUpdate#74]
When I install Legacy Update, the inbuilt updater of Windows XP x64 works fine.
The website loads for a few seconds and then throws:

"Legacy Update isn't installed, or needs to be updated."

I have Internet Explorer 8 installed, if that makes any difference.

**Comment by kirb** [comment]
Are you running 32 or 64-bit Internet Explorer? The homepage should tell you if it’s running as 64-bit. Legacy Update only runs on 32-bit IE. The start menu/control panel shortcut will open the correct IE for you.

If you are launching from the shortcut and still not having luck, try this in a command prompt:

```
cd "C:\Program Files (x86)\Legacy Update"
regsvr32 /u LegacyUpdate.dll
regsvr32 LegacyUpdate.dll
```

That will re-register the dll in the registry. You might get a useful error message out of that, otherwise it should say it was successful.

**Comment by lichtmetzger** [comment]
The start menu shortcut opens up the 64bit Internet Explorer. With the 32bit IE it works! :)

**Comment by kirb** [comment]
That’s weird, it should be launching 32-bit IE because it’s a 32-bit dll that handles opening IE. Maybe XP/Server 2003 64-bit handles that differently than Vista and up. Will look into that.

**Comment by stdin82** [comment]
x64 wuweb.dll uses `CLSCTX_LOCAL_SERVER | CLSCTX_ACTIVATE_X86_SERVER` for CoCreateInstance

**Comment by kirb** [comment]
@stdin82 Good catch, thank you! `CLSCTX_ACTIVATE_X86_SERVER` is [documented](https://learn.microsoft.com/en-us/windows/win32/api/wtypesbase/ne-wtypesbase-clsctx) but not present in the SDK, `CLSCTX_ACTIVATE_32_BIT_SERVER` seems to be the same though (`0x40000`).
